"""empty message

Revision ID: 03ab932981f6
Revises: 772d25570d7f
Create Date: 2024-11-12 20:30:55.241595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ab932981f6'
down_revision: Union[str, None] = '772d25570d7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profiles', sa.Column('user_profile_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_profiles', 'user_profile_id')
    # ### end Alembic commands ###
