"""create messages table

Revision ID: 51dcc1f5dddf
Revises: 60446889987e
Create Date: 2025-04-01 21:55:22.459930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dcc1f5dddf'
down_revision: Union[str, None] = '60446889987e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=485), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users_profiles.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_unique_constraint(None, 'post_comments', ['id'])
    op.create_unique_constraint(None, 'post_likes', ['id'])
    op.create_unique_constraint(None, 'user_subscribers', ['id'])
    op.create_unique_constraint(None, 'user_subscribes', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'users_photos', ['id'])
    op.create_unique_constraint(None, 'users_posts', ['id'])
    op.create_unique_constraint(None, 'users_profiles', ['id'])
    op.create_unique_constraint(None, 'users_protect', ['id'])
    op.create_unique_constraint(None, 'users_refresh_tokens', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_refresh_tokens', type_='unique')
    op.drop_constraint(None, 'users_protect', type_='unique')
    op.drop_constraint(None, 'users_profiles', type_='unique')
    op.drop_constraint(None, 'users_posts', type_='unique')
    op.drop_constraint(None, 'users_photos', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_subscribes', type_='unique')
    op.drop_constraint(None, 'user_subscribers', type_='unique')
    op.drop_constraint(None, 'post_likes', type_='unique')
    op.drop_constraint(None, 'post_comments', type_='unique')
    op.drop_table('messages')
    # ### end Alembic commands ###
