"""add photos and posts relationship

Revision ID: a301e2dbfbf6
Revises: 3bc50294e5da
Create Date: 2024-12-10 20:14:59.217245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a301e2dbfbf6'
down_revision: Union[str, None] = '3bc50294e5da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
