"""add post_id_fkey and post_id

Revision ID: ac4f0cf45b11
Revises: 1eb2829123e1
Create Date: 2024-12-05 22:24:30.482926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4f0cf45b11'
down_revision: Union[str, None] = '1eb2829123e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_photos', sa.Column('post_id_fkey', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'users_photos', ['id'])
    op.drop_constraint('users_photos_post_id_fkey', 'users_photos', type_='foreignkey')
    op.create_foreign_key(None, 'users_photos', 'users_posts', ['post_id_fkey'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_photos', type_='foreignkey')
    op.create_foreign_key('users_photos_post_id_fkey', 'users_photos', 'users_posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'users_photos', type_='unique')
    op.drop_column('users_photos', 'post_id_fkey')
    # ### end Alembic commands ###
