"""add posts table

Revision ID: af2e2273187f
Revises: 5037ea819d2c
Create Date: 2024-12-03 21:30:04.786093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af2e2273187f'
down_revision: Union[str, None] = '5037ea819d2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('desscription', sa.String(length=20), nullable=True),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('file_link', sa.String(), nullable=False),
    sa.Column('file_weight', sa.LargeBinary(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_posts')
    # ### end Alembic commands ###
